const languages = {'fa': 'فارسی', 'ar': 'العربية', 'en': 'English', 'zh': '中文'};
const words = <String, List<String>>{
  'unknownSize': ['حجم نامشخص', 'الحجم غير معروف', 'Size unknown', '大小未知'],
  'approximately': ['حدود ', 'حوالي ', 'About ', '约 '],
  'noPreview': [
    'تصویر ویدیو در دسترس نیست',
    'الصورة غير متاحة',
    'Preview unavailable',
    '预览不可用',
  ],
  'sizeHint': [
    'حجم شامل صدا است؛ مقدارهای «حدود» تخمینی‌اند و حجم نهایی پس از ترکیب ممکن است کمی متفاوت باشد.',
    'الحجم يشمل الصوت؛ القيم التقريبية والحجم النهائي قد تختلف.',
    'Size includes audio. Estimates and the final merged file size may differ.',
    '大小包含音频；估计值与合并后的最终大小可能不同。',
  ],
  'copyAddress': [
    'کپی آدرس کیف پول',
    'نسخ عنوان المحفظة',
    'Copy wallet address',
    '复制钱包地址',
  ],
  'addressCopied': ['آدرس کپی شد', 'تم نسخ العنوان', 'Address copied', '地址已复制'],
  'walletNetworkHint': [
    'فقط ارز و شبکهٔ نمایش‌داده‌شده را استفاده کنید.',
    'استخدم العملة والشبكة المعروضتين فقط.',
    'Use only the currency and network shown above.',
    '请仅使用上述币种与网络。',
  ],
  'support': ['حمایت از ویدورا', 'دعم فيدورا', 'Support Vidora', '支持 Vidora'],
  'supportBody': [
    'اگر ویدورا برایتان مفید بوده، می‌توانید به ادامهٔ توسعهٔ آن کمک کنید. حمایت کاملاً اختیاری است و همهٔ امکانات رایگان می‌مانند.',
    'إذا أفادك فيدورا، يمكنك دعم تطويره. الدعم اختياري وجميع الميزات تبقى مجانية.',
    'If Vidora helps you, you can support its continued development. Support is optional and all features remain free.',
    '如果 Vidora 对您有帮助，欢迎支持后续开发。支持完全自愿，所有功能仍然免费。',
  ],
  'supportUnavailable': [
    'لینک حمایت به‌زودی اضافه می‌شود.',
    'سيُضاف رابط الدعم قريباً.',
    'A support link will be added soon.',
    '支持链接即将添加。',
  ],
  'supportOpen': [
    'رفتن به صفحهٔ حمایت',
    'فتح صفحة الدعم',
    'Open support page',
    '打开支持页面',
  ],
  'supportPrivacy': [
    'صفحهٔ حمایت در مرورگر باز می‌شود. لینک ویدیو، کوکی و فایل‌های شما به آن ارسال نمی‌شوند.',
    'تفتح الصفحة في المتصفح؛ لا تُرسل روابط الفيديو أو الكوكيز أو ملفاتك إليها.',
    'The support page opens in your browser. Your video links, cookies and files are never sent to it.',
    '支持页面在浏览器中打开，不会向其发送视频链接、Cookie 或文件。',
  ],
  'supportError': [
    'مرورگر باز نشد؛ لینک زیر را کپی و در مرورگر باز کنید.',
    'تعذر فتح المتصفح؛ انسخ الرابط أدناه وافتحه.',
    'Could not open your browser. Copy the link below and open it manually.',
    '无法打开浏览器，请复制下方链接手动打开。',
  ],
  'close': ['بستن', 'إغلاق', 'Close', '关闭'],
  'cookies': [
    'کوکی اختیاری مرورگر',
    'ملف تعريف ارتباط اختياري',
    'Optional browser cookies',
    '可选浏览器 Cookie',
  ],
  'noCookies': [
    'بدون فایل کوکی',
    'بدون ملف كوكي',
    'No cookie file',
    '未选择 Cookie 文件',
  ],
  'chooseCookies': [
    'انتخاب فایل کوکی',
    'اختر ملف كوكي',
    'Choose cookie file',
    '选择 Cookie 文件',
  ],
  'clearCookies': [
    'قطع استفاده از کوکی برای بررسی بعدی',
    'إيقاف استخدام الكوكي للفحص التالي',
    'Disable cookies for the next check',
    '下次检查不使用 Cookie',
  ],
  'cookiesHelp': [
    'فایل cookies.txt با فرمت Netscape مربوط به همین سایت را انتخاب کنید. مرورگر و برنامه باید از همان مسیر اتصال استفاده کنند. فقط کوکی‌های مرتبط با سایت انتخاب‌شده استفاده می‌شوند؛ فایل اصلی تغییر نمی‌کند. کپی موقت پس از بررسی یا دانلود پاک می‌شود. انتخاب برای همین اجرای برنامه است و کارهای موجود در صف نشست زمان بررسی را نگه می‌دارند. کوکی را در چت نفرستید.',
    'اختر ملف cookies.txt بصيغة Netscape لهذا الموقع. استخدم الاتصال نفسه في المتصفح والتطبيق. تُستخدم كوكيز الموقع فقط؛ الملف الأصلي لا يتغير والنسخة المؤقتة تُحذف. الاختيار لهذه الجلسة؛ مهام القائمة تحتفظ بجلسة الفحص. لا ترسل الملف في الدردشة.',
    'Choose a Netscape cookies.txt file for this site. Use the same connection in your browser and this app. Only matching site cookies are used; the original is unchanged and temporary copies are deleted. Selection lasts for this app session; queued jobs retain their inspected session. Do not send the file in chat.',
    '请选择该网站的 Netscape 格式 cookies.txt，浏览器和应用须使用同一连接。仅使用匹配网站的 Cookie；原文件不变，临时副本将被删除。选择仅用于本次运行，队列任务保留检查时的会话。请勿在聊天中发送该文件。',
  ],
  'invalidCookies': [
    'فایل کوکی معتبر Netscape خوانده نشد. فایل مربوط به سایت را دوباره از مرورگر صادر کنید.',
    'تعذر قراءة ملف Netscape صالح؛ صدّره مرة أخرى من المتصفح.',
    'Cannot read a valid Netscape cookie file. Export it again from your browser.',
    '无法读取有效的 Netscape Cookie 文件，请从浏览器重新导出。',
  ],
  'noMatchingCookies': [
    'در فایل، کوکی معتبر و منقضی‌نشدهٔ این سایت پیدا نشد. نشست مرورگر را تازه و کوکی همین سایت را دوباره صادر کنید.',
    'لا توجد كوكيز صالحة لهذا الموقع؛ حدّث الجلسة وصدّرها مجدداً.',
    'No unexpired cookies match this site. Refresh the browser session and export that site’s cookies again.',
    '文件中没有匹配该网站的有效 Cookie，请刷新浏览器会话并重新导出。',
  ],
  'automatic': [
    'خودکار (سیستم، سپس بدون پراکسی در صورت خطای اتصال)',
    'تلقائي (النظام ثم بدون وكيل عند خطأ الاتصال)',
    'Automatic (system, then no proxy on connection failure)',
    '自动（系统，连接失败时尝试无代理）',
  ],
  'connection': ['روش اتصال', 'طريقة الاتصال', 'Connection', '连接方式'],
  'system': [
    'تنظیمات پراکسی سیستم',
    'إعدادات وكيل النظام',
    'System proxy settings',
    '系统代理设置',
  ],
  'direct': [
    'مستقیم (بدون پراکسی)',
    'مباشر (بدون وكيل)',
    'Direct (no proxy)',
    '直连（无代理）',
  ],
  'custom': ['پراکسی مشخص', 'وكيل مخصص', 'Custom proxy', '自定义代理'],
  'proxyAddress': [
    'آدرس پراکسی HTTP یا SOCKS5',
    'عنوان وكيل HTTP أو SOCKS5',
    'HTTP or SOCKS5 proxy URL',
    'HTTP 或 SOCKS5 代理地址',
  ],
  'proxyHint': [
    'مثال: http://127.0.0.1:12334 — پراکسی باید روشن باشد؛ اتصال مستقیم نیازمند دسترسی شبکه به سایت است.',
    'مثال: http://127.0.0.1:12334 — يجب تشغيل الوكيل؛ الاتصال المباشر يتطلب الوصول إلى الموقع.',
    'Example: http://127.0.0.1:12334 — the proxy must be running. Direct mode requires network access to the site.',
    '示例：http://127.0.0.1:12334 — 代理必须已启动，直连模式需要网络能访问该网站。',
  ],
  'proxy': [
    'اتصال به پراکسی برقرار نشد. برنامهٔ پراکسی را روشن و آدرس و پورت را بررسی کنید، یا روش اتصال را تغییر دهید.',
    'تعذر الاتصال بالوكيل. شغّله وتحقق من العنوان والمنفذ أو غيّر طريقة الاتصال.',
    'Cannot connect to the proxy. Start it and check the address and port, or change connection mode.',
    '无法连接代理。请启动代理并检查地址和端口，或更改连接方式。',
  ],
  'invalidProxy': [
    'آدرس معتبر http:// یا https:// یا socks5:// بدون نام کاربری و رمز وارد کنید.',
    'أدخل عنوان http:// أو https:// أو socks5:// صالحاً بدون بيانات تسجيل دخول.',
    'Enter a valid http://, https:// or socks5:// proxy URL without credentials.',
    '请输入有效的 http://、https:// 或 socks5:// 代理地址（不含登录信息）。',
  ],
  'bot': [
    'یوتیوب تأیید ضدربات می‌خواهد. لینک را در مرورگر با همین اتصال باز و تأیید احتمالی را خودتان انجام دهید، سپس کوکی همان نشست را انتخاب کنید. موفقیت تضمین‌شده نیست.',
    'يتطلب YouTube تحققاً. افتح الرابط في المتصفح بنفس الاتصال وأكمل التحقق بنفسك ثم اختر كوكيز الجلسة. النجاح غير مضمون.',
    'YouTube requires an anti-bot check. Open the link in your browser on the same connection, complete any check yourself, then select that session’s cookies. Success is not guaranteed.',
    'YouTube 要求反机器人验证。请使用相同连接在浏览器打开链接，自行完成验证，然后选择该会话的 Cookie。无法保证成功。',
  ],
  'restricted': [
    'ویدیو در دسترس نیست یا به ورود، سن مجاز، عضویت یا منطقهٔ خاص نیاز دارد.',
    'الفيديو غير متاح أو يتطلب تسجيل دخول أو عمراً مناسباً أو عضوية أو منطقة محددة.',
    'Video is unavailable or requires sign-in, age verification, membership or a supported region.',
    '视频不可用，或需要登录、年龄验证、会员资格或支持的地区。',
  ],
  'auto': [
    'نامشخص / خودکار',
    'غير محددة / تلقائي',
    'Unknown / automatic',
    '未知 / 自动',
  ],
  'app': ['ویدورا', 'فيدورا', 'Vidora', 'Vidora'],
  'privacy': [
    'پردازش و ذخیره روی دستگاه شما؛ پشتیبانی سایت‌ها به بهترین تلاش',
    'المعالجة والحفظ على جهازك؛ دعم المواقع حسب الإمكان',
    'Processing and storage on your device; site support is best effort',
    '在您的设备上处理和保存；尽力支持各网站',
  ],
  'link': [
    'لینک ویدیو را اینجا بچسبانید',
    'الصق رابط الفيديو هنا',
    'Paste a video URL here',
    '在此粘贴视频链接',
  ],
  'inspect': ['بررسی لینک', 'فحص الرابط', 'Check link', '检查链接'],
  'quality': ['کیفیت', 'الجودة', 'Quality', '画质'],
  'format': ['فرمت خروجی', 'صيغة الملف', 'Output format', '输出格式'],
  'folder': ['انتخاب پوشه', 'اختر مجلداً', 'Choose folder', '选择文件夹'],
  'download': [
    'افزودن به صف دانلود',
    'إضافة إلى قائمة التنزيل',
    'Add to download queue',
    '加入下载队列',
  ],
  'queue': ['صف دانلود', 'قائمة التنزيل', 'Download queue', '下载队列'],
  'empty': [
    'هنوز دانلودی اضافه نشده',
    'لا توجد تنزيلات بعد',
    'No downloads yet',
    '尚无下载任务',
  ],
  'cancel': ['لغو', 'إلغاء', 'Cancel', '取消'],
  'retry': ['تلاش دوباره', 'إعادة المحاولة', 'Retry', '重试'],
  'open': ['باز کردن پوشه', 'فتح المجلد', 'Open folder', '打开文件夹'],
  'waiting': ['در انتظار', 'في الانتظار', 'Waiting', '等待中'],
  'running': [
    'در حال دانلود / پردازش',
    'تنزيل / معالجة',
    'Downloading / processing',
    '下载 / 处理中',
  ],
  'done': ['پایان دانلود', 'اكتمل التنزيل', 'Completed', '已完成'],
  'cancelled': ['لغو شده', 'تم الإلغاء', 'Cancelled', '已取消'],
  'failed': ['خطا', 'خطأ', 'Failed', '失败'],
  'invalid': [
    'لینک معتبر HTTP یا HTTPS وارد کنید.',
    'أدخل رابط HTTP أو HTTPS صالحاً.',
    'Enter a valid HTTP or HTTPS URL.',
    '请输入有效的 HTTP 或 HTTPS 链接。',
  ],
  'unsupported': [
    'این سایت یا نوع لینک پشتیبانی نمی‌شود.',
    'هذا الموقع أو الرابط غير مدعوم.',
    'This site or URL type is unsupported.',
    '不支持此网站或链接类型。',
  ],
  'network': [
    'اتصال به سایت برقرار نشد؛ اینترنت و دسترسی به سایت را بررسی کنید.',
    'تعذر الاتصال بالموقع؛ تحقق من الشبكة والوصول.',
    'Could not reach the site. Check your connection and site access.',
    '无法连接网站，请检查网络和网站访问权限。',
  ],
  'extraction': [
    'استخراج یا تبدیل ویدیو ناموفق بود؛ لینک ممکن است محدود باشد یا موتور به به‌روزرسانی نیاز داشته باشد.',
    'تعذر استخراج أو تحويل الفيديو؛ قد يكون مقيداً أو يحتاج المحرك إلى تحديث.',
    'Extraction or conversion failed. The video may be restricted or the engine may need updating.',
    '提取或转换失败。视频可能受限，或下载引擎需要更新。',
  ],
  'tools': [
    'موتورهای همراه برنامه پیدا نشدند؛ بستهٔ کامل برنامه را استفاده کنید.',
    'محركات التطبيق غير موجودة؛ استخدم الحزمة الكاملة.',
    'Bundled tools are missing. Use the complete app package.',
    '缺少随附工具，请使用完整应用程序包。',
  ],
  'storage': [
    'ذخیرهٔ فایل ممکن نشد؛ مجوز و فضای پوشه را بررسی کنید.',
    'تعذر حفظ الملف؛ تحقق من الأذونات والمساحة.',
    'Cannot save the file. Check folder permissions and free space.',
    '无法保存文件，请检查文件夹权限和可用空间。',
  ],
  'merge': [
    'صدا با FFmpeg محلی ترکیب می‌شود',
    'سيتم دمج الصوت بواسطة FFmpeg محلياً',
    'Audio will be merged locally with FFmpeg',
    '将使用本地 FFmpeg 合并音频',
  ],
};
String tr(String locale, String key) =>
    words[key]?[['fa', 'ar', 'en', 'zh'].indexOf(locale)] ?? key;
