const languages = {'en': 'English', 'fa': 'فارسی', 'ar': 'العربية', 'zh': '中文'};
const words = <String, List<String>>{
  'about': ['دربارهٔ ویدورا', 'حول فيدورا', 'About Vidora', '关于 Vidora'],
  'aboutBody': [
    'ویدورا برنامه‌ای رایگان برای دانلود ویدیوست. لینک را وارد کنید، کیفیت را انتخاب کنید و فایل را روی دستگاه خودتان ذخیره کنید.',
    'فيدورا تطبيق مجاني لتنزيل الفيديو. الصق الرابط، اختر الجودة واحفظ الفيديو على جهازك.',
    'Vidora is a free video downloader. Paste a link, choose a quality and save the video to your device.',
    'Vidora 是一款免费的视频下载工具。粘贴链接、选择画质，就能把视频保存到自己的设备上。',
  ],
  'aboutAuthor': [
    'نویسندهٔ برنامه: ذوالفقاری',
    'مؤلف التطبيق: Zolfaghari',
    'Author: Zolfaghari',
    '作者：Zolfaghari',
  ],
  'aboutSupport': [
    'اگر ویدورا به کارتان آمده، با حمایتتان به بهتر شدن برنامه کمک کنید. استفاده از همهٔ امکانات رایگان است.',
    'إذا أفادك فيدورا، يمكنك المساهمة في تطويره. جميع الميزات مجانية، والدعم اختياري.',
    'If Vidora has been useful to you, a donation helps me keep improving it. Every feature is free to use.',
    '如果 Vidora 帮到了您，欢迎支持后续开发。所有功能免费，支持完全自愿。',
  ],
  'unknownSize': ['حجم نامشخص', 'الحجم غير معروف', 'Size unknown', '大小未知'],
  'approximately': ['حدود ', 'حوالي ', 'About ', '约 '],
  'noPreview': [
    'تصویر ویدیو در دسترس نیست',
    'الصورة غير متاحة',
    'Preview unavailable',
    '预览不可用',
  ],
  'sizeHint': [
    'حجم نمایش‌داده‌شده شامل صدا هم می‌شود. حجم نهایی ممکن است کمی فرق کند.',
    'الحجم المعروض يشمل الصوت. قد يختلف حجم الملف النهائي قليلاً.',
    'The size includes audio. The saved file may be slightly larger or smaller.',
    '显示的大小包含音频，最终文件大小可能略有不同。',
  ],
  'copyAddress': [
    'کپی آدرس کیف پول',
    'نسخ عنوان المحفظة',
    'Copy wallet address',
    '复制钱包地址',
  ],
  'addressCopied': ['آدرس کپی شد', 'تم نسخ العنوان', 'Address copied', '地址已复制'],
  'walletNetworkHint': [
    'فقط ارز و شبکهٔ نمایش‌داده‌شده را استفاده کنید.',
    'استخدم العملة والشبكة المعروضتين فقط.',
    'Use only the currency and network shown above.',
    '请仅使用上述币种与网络。',
  ],
  'support': ['حمایت از ویدورا', 'دعم فيدورا', 'Support Vidora', '支持 Vidora'],
  'supportBody': [
    'حمایت شما کمک می‌کند وقت بیشتری برای ویدورا بگذارم. هر مبلغی که مایل باشید؛ برنامه برای همه رایگان می‌ماند.',
    'دعمك يساعدني على تخصيص وقت أكبر لفيدورا. اختر المبلغ المناسب لك؛ يظل التطبيق مجانياً للجميع.',
    'Your support gives me more time to work on Vidora. Give whatever you like; the app stays free for everyone.',
    '您的支持让我能投入更多时间改进 Vidora。金额随意，应用始终免费。',
  ],
  'supportUnavailable': [
    'لینک حمایت به‌زودی اضافه می‌شود.',
    'سيُضاف رابط الدعم قريباً.',
    'A support link will be added soon.',
    '支持链接即将添加。',
  ],
  'supportOpen': [
    'رفتن به صفحهٔ حمایت',
    'فتح صفحة الدعم',
    'Open support page',
    '打开支持页面',
  ],
  'supportPrivacy': [
    'صفحهٔ حمایت در مرورگر باز می‌شود. لینک ویدیو، کوکی و فایل‌های شما به آن ارسال نمی‌شوند.',
    'تفتح الصفحة في المتصفح؛ لا تُرسل روابط الفيديو أو الكوكيز أو ملفاتك إليها.',
    'The support page opens in your browser. Your video links, cookies and files are never sent to it.',
    '支持页面在浏览器中打开，不会向其发送视频链接、Cookie 或文件。',
  ],
  'supportError': [
    'مرورگر باز نشد؛ لینک زیر را کپی و در مرورگر باز کنید.',
    'تعذر فتح المتصفح؛ انسخ الرابط أدناه وافتحه.',
    'Could not open your browser. Copy the link below and open it manually.',
    '无法打开浏览器，请复制下方链接手动打开。',
  ],
  'close': ['بستن', 'إغلاق', 'Close', '关闭'],
  'cookies': [
    'کوکی اختیاری مرورگر',
    'ملف تعريف ارتباط اختياري',
    'Optional browser cookies',
    '可选浏览器 Cookie',
  ],
  'noCookies': [
    'بدون فایل کوکی',
    'بدون ملف كوكي',
    'No cookie file',
    '未选择 Cookie 文件',
  ],
  'chooseCookies': [
    'انتخاب فایل کوکی',
    'اختر ملف كوكي',
    'Choose cookie file',
    '选择 Cookie 文件',
  ],
  'clearCookies': [
    'قطع استفاده از کوکی برای بررسی بعدی',
    'إيقاف استخدام الكوكي للفحص التالي',
    'Disable cookies for the next check',
    '下次检查不使用 Cookie',
  ],
  'cookiesHelp': [
    'برای سایت‌هایی که نیاز به ورود دارند، فایل کوکی همان سایت را انتخاب کنید. مرورگر و ویدورا باید از یک VPN یا پراکسی استفاده کنند. فایل اصلی دست‌نخورده می‌ماند و کپی موقت بعد از دانلود پاک می‌شود. فایل انتخابی فقط برای همین اجرای برنامه است؛ دانلودهای داخل صف از کوکی زمان بررسی لینک استفاده می‌کنند.',
    'إذا تطلب الموقع تسجيل الدخول، اختر ملف الكوكيز الخاص به. استخدم VPN أو الوكيل نفسه في المتصفح وفيدورا. يبقى الملف الأصلي كما هو وتُحذف النسخة المؤقتة بعد التنزيل. يُستخدم الملف في هذه الجلسة فقط؛ تحتفظ التنزيلات في القائمة بكوكيز وقت فحص الرابط.',
    'For sites that need a login, choose a cookie file from that site. Use the same VPN or proxy in your browser and Vidora. Your original file stays untouched and the temporary copy is deleted after use. The file is used for this session only; queued downloads keep the cookies from when their links were checked.',
    '如果网站要求登录，请选择该网站的 Cookie 文件。浏览器和 Vidora 应使用相同的 VPN 或代理。原文件保持不变，临时副本在使用后删除。文件仅用于本次运行；队列中的下载保留检查链接时的 Cookie。',
  ],
  'cookiesGuideTitle': [
    'راهنمای گرفتن کوکی با افزونه',
    'كيفية تصدير الكوكيز بالإضافة',
    'How to export cookies with the extension',
    '如何使用扩展导出 Cookie',
  ],
  'cookiesGuide': [
    '۱. لینک ویدیو را در مرورگر باز کنید؛ اگر لازم بود وارد حساب شوید و تأیید سایت را انجام دهید.\n\n۲. در همان تب، از منوی افزونه‌های مرورگر، Get cookies.txt LOCALLY را باز کنید.\n\n۳. گزینهٔ Export Format را روی Netscape بگذارید و Export یا Export As را بزنید تا کوکی‌های همین سایت در یک فایل .txt ذخیره شوند.\n\n۴. در ویدورا «انتخاب فایل کوکی» را بزنید و فایل ذخیره‌شده را انتخاب کنید؛ نام فایل لازم نیست حتماً cookies.txt باشد. سپس «بررسی لینک» را دوباره بزنید.\n\nاگر پیام کوکی نامعتبر یا منقضی دیدید، صفحهٔ سایت را در مرورگر تازه کنید، دوباره خروجی بگیرید و فایل جدید را انتخاب کنید.',
    '١. افتح رابط الفيديو في المتصفح؛ سجّل الدخول وأكمل تحقق الموقع إذا لزم الأمر.\n\n٢. في التبويب نفسه، افتح Get cookies.txt LOCALLY من قائمة إضافات المتصفح.\n\n٣. اضبط Export Format على Netscape واضغط Export أو Export As لحفظ كوكيز هذا الموقع في ملف .txt.\n\n٤. اضغط «اختر ملف كوكي» في فيدورا وحدد الملف المحفوظ؛ ليس ضرورياً أن يكون اسمه cookies.txt. ثم افحص الرابط مجدداً.\n\nإذا ظهر خطأ كوكيز غير صالحة أو منتهية، حدّث صفحة الموقع وصدّر ملفاً جديداً واختره.',
    '1. Open the video link in your browser. Sign in and complete any site check if needed.\n\n2. On that same tab, open Get cookies.txt LOCALLY from your browser’s extensions menu.\n\n3. Set Export Format to Netscape and click Export or Export As to save this site’s cookies as a .txt file.\n\n4. Click “Choose cookie file” in Vidora and select the saved file; it does not have to be named cookies.txt. Then inspect the link again.\n\nIf cookies are invalid or expired, refresh the site in your browser, export a fresh file and select it again.',
    '1. 在浏览器中打开视频链接。如有需要，请登录并完成网站验证。\n\n2. 在同一标签页中，从浏览器扩展菜单打开 Get cookies.txt LOCALLY。\n\n3. 将 Export Format 设置为 Netscape，点击 Export 或 Export As，将当前网站的 Cookie 保存为 .txt 文件。\n\n4. 在 Vidora 中点击“选择 Cookie 文件”并选择保存的文件；文件名无需为 cookies.txt。然后重新检查链接。\n\n如果提示 Cookie 无效或过期，请刷新浏览器中的网站页面，重新导出并选择新文件。',
  ],
  'invalidCookies': [
    'فایل کوکی معتبر Netscape خوانده نشد. فایل مربوط به سایت را دوباره از مرورگر صادر کنید.',
    'تعذر قراءة ملف Netscape صالح؛ صدّره مرة أخرى من المتصفح.',
    'Cannot read a valid Netscape cookie file. Export it again from your browser.',
    '无法读取有效的 Netscape Cookie 文件，请从浏览器重新导出。',
  ],
  'noMatchingCookies': [
    'در فایل، کوکی معتبر و منقضی‌نشدهٔ این سایت پیدا نشد. نشست مرورگر را تازه و کوکی همین سایت را دوباره صادر کنید.',
    'لا توجد كوكيز صالحة لهذا الموقع؛ حدّث الجلسة وصدّرها مجدداً.',
    'No unexpired cookies match this site. Refresh the browser session and export that site’s cookies again.',
    '文件中没有匹配该网站的有效 Cookie，请刷新浏览器会话并重新导出。',
  ],
  'automatic': ['خودکار', 'تلقائي', 'Automatic', '自动'],
  'connection': ['روش اتصال', 'طريقة الاتصال', 'Connection', '连接方式'],
  'system': [
    'تنظیمات پراکسی سیستم',
    'إعدادات وكيل النظام',
    'System proxy settings',
    '系统代理设置',
  ],
  'direct': [
    'مستقیم (بدون پراکسی)',
    'مباشر (بدون وكيل)',
    'Direct (no proxy)',
    '直连（无代理）',
  ],
  'custom': ['پراکسی مشخص', 'وكيل مخصص', 'Custom proxy', '自定义代理'],
  'proxyAddress': [
    'آدرس پراکسی HTTP یا SOCKS5',
    'عنوان وكيل HTTP أو SOCKS5',
    'HTTP or SOCKS5 proxy URL',
    'HTTP 或 SOCKS5 代理地址',
  ],
  'proxyHint': [
    'در حالت خودکار، اول پراکسی سیستم امتحان می‌شود و اگر اتصال برقرار نشد، برنامه بدون پراکسی تلاش می‌کند. برای پراکسی مشخص، آدرس و پورت را وارد کنید؛ مثلاً http://127.0.0.1:12334.',
    'في الوضع التلقائي، يُجرّب وكيل النظام أولاً ثم الاتصال المباشر إذا فشل. للوكيل المخصص، أدخل العنوان والمنفذ؛ مثلاً http://127.0.0.1:12334.',
    'Automatic mode tries the system proxy first, then a direct connection if it fails. For a custom proxy, enter its address and port, such as http://127.0.0.1:12334.',
    '自动模式先尝试系统代理，连接失败后尝试直连。使用自定义代理时，请输入地址和端口，例如 http://127.0.0.1:12334。',
  ],
  'proxy': [
    'اتصال به پراکسی برقرار نشد. برنامهٔ پراکسی را روشن و آدرس و پورت را بررسی کنید، یا روش اتصال را تغییر دهید.',
    'تعذر الاتصال بالوكيل. شغّله وتحقق من العنوان والمنفذ أو غيّر طريقة الاتصال.',
    'Cannot connect to the proxy. Start it and check the address and port, or change connection mode.',
    '无法连接代理。请启动代理并检查地址和端口，或更改连接方式。',
  ],
  'invalidProxy': [
    'آدرس معتبر http:// یا https:// یا socks5:// بدون نام کاربری و رمز وارد کنید.',
    'أدخل عنوان http:// أو https:// أو socks5:// صالحاً بدون بيانات تسجيل دخول.',
    'Enter a valid http://, https:// or socks5:// proxy URL without credentials.',
    '请输入有效的 http://、https:// 或 socks5:// 代理地址（不含登录信息）。',
  ],
  'bot': [
    'یوتیوب تأیید ضدربات می‌خواهد. لینک را در مرورگر با همین اتصال باز و تأیید احتمالی را خودتان انجام دهید، سپس کوکی همان نشست را انتخاب کنید. موفقیت تضمین‌شده نیست.',
    'يتطلب YouTube تحققاً. افتح الرابط في المتصفح بنفس الاتصال وأكمل التحقق بنفسك ثم اختر كوكيز الجلسة. النجاح غير مضمون.',
    'YouTube requires an anti-bot check. Open the link in your browser on the same connection, complete any check yourself, then select that session’s cookies. Success is not guaranteed.',
    'YouTube 要求反机器人验证。请使用相同连接在浏览器打开链接，自行完成验证，然后选择该会话的 Cookie。无法保证成功。',
  ],
  'restricted': [
    'ویدیو در دسترس نیست یا به ورود، سن مجاز، عضویت یا منطقهٔ خاص نیاز دارد.',
    'الفيديو غير متاح أو يتطلب تسجيل دخول أو عمراً مناسباً أو عضوية أو منطقة محددة.',
    'Video is unavailable or requires sign-in, age verification, membership or a supported region.',
    '视频不可用，或需要登录、年龄验证、会员资格或支持的地区。',
  ],
  'auto': [
    'نامشخص / خودکار',
    'غير محددة / تلقائي',
    'Unknown / automatic',
    '未知 / 自动',
  ],
  'app': ['ویدورا', 'فيدورا', 'Vidora', 'Vidora'],
  'privacy': [
    'ویدیوها روی دستگاه خودتان ذخیره می‌شوند.',
    'تُحفظ الفيديوهات على جهازك.',
    'Videos are saved to your device.',
    '视频保存在您自己的设备上。',
  ],
  'link': [
    'لینک ویدیو را اینجا بچسبانید',
    'الصق رابط الفيديو هنا',
    'Paste a video URL here',
    '在此粘贴视频链接',
  ],
  'inspect': ['بررسی لینک', 'فحص الرابط', 'Check link', '检查链接'],
  'quality': ['کیفیت', 'الجودة', 'Quality', '画质'],
  'format': ['فرمت خروجی', 'صيغة الملف', 'Output format', '输出格式'],
  'incompatibleFormat': [
    'فرمت خروجی با این کیفیت سازگار نیست؛ فرمت دیگری انتخاب کنید.',
    'صيغة الإخراج غير متوافقة مع هذه الجودة؛ اختر صيغة أخرى.',
    'This output format is incompatible with the selected quality. Choose another format.',
    '输出格式与所选画质不兼容，请选择其他格式。',
  ],
  'folder': ['انتخاب پوشه', 'اختر مجلداً', 'Choose folder', '选择文件夹'],
  'download': [
    'افزودن به صف دانلود',
    'إضافة إلى قائمة التنزيل',
    'Add to download queue',
    '加入下载队列',
  ],
  'queue': ['صف دانلود', 'قائمة التنزيل', 'Download queue', '下载队列'],
  'empty': [
    'هنوز دانلودی اضافه نشده',
    'لا توجد تنزيلات بعد',
    'No downloads yet',
    '尚无下载任务',
  ],
  'cancel': ['لغو', 'إلغاء', 'Cancel', '取消'],
  'retry': ['تلاش دوباره', 'إعادة المحاولة', 'Retry', '重试'],
  'open': ['باز کردن پوشه', 'فتح المجلد', 'Open folder', '打开文件夹'],
  'waiting': ['در انتظار', 'في الانتظار', 'Waiting', '等待中'],
  'running': [
    'در حال دانلود / پردازش',
    'تنزيل / معالجة',
    'Downloading / processing',
    '下载 / 处理中',
  ],
  'done': ['پایان دانلود', 'اكتمل التنزيل', 'Completed', '已完成'],
  'cancelled': ['لغو شده', 'تم الإلغاء', 'Cancelled', '已取消'],
  'failed': ['خطا', 'خطأ', 'Failed', '失败'],
  'invalid': [
    'لینک معتبر HTTP یا HTTPS وارد کنید.',
    'أدخل رابط HTTP أو HTTPS صالحاً.',
    'Enter a valid HTTP or HTTPS URL.',
    '请输入有效的 HTTP 或 HTTPS 链接。',
  ],
  'unsupported': [
    'این سایت یا نوع لینک پشتیبانی نمی‌شود.',
    'هذا الموقع أو الرابط غير مدعوم.',
    'This site or URL type is unsupported.',
    '不支持此网站或链接类型。',
  ],
  'network': [
    'اتصال به سایت برقرار نشد؛ اینترنت و دسترسی به سایت را بررسی کنید.',
    'تعذر الاتصال بالموقع؛ تحقق من الشبكة والوصول.',
    'Could not reach the site. Check your connection and site access.',
    '无法连接网站，请检查网络和网站访问权限。',
  ],
  'extraction': [
    'ویدیو دانلود نشد. دوباره امتحان کنید؛ اگر خطا تکرار شد، لینک دیگری را بررسی کنید یا برنامه را به‌روز کنید.',
    'تعذر تنزيل الفيديو. حاول مجدداً؛ إذا استمر الخطأ، جرّب رابطاً آخر أو حدّث التطبيق.',
    'The video could not be downloaded. Try again. If it keeps failing, try another link or update the app.',
    '视频下载失败，请重试。如果仍然失败，请尝试其他链接或更新应用。',
  ],
  'tools': [
    'بعضی فایل‌های برنامه پیدا نشدند. ویدورا را با بستهٔ کامل دوباره نصب کنید.',
    'بعض ملفات التطبيق مفقودة. أعد تثبيت فيدورا باستخدام الحزمة الكاملة.',
    'Some app files are missing. Reinstall Vidora using the complete package.',
    '部分应用文件缺失，请使用完整安装包重新安装 Vidora。',
  ],
  'storage': [
    'ذخیرهٔ فایل ممکن نشد؛ مجوز و فضای پوشه را بررسی کنید.',
    'تعذر حفظ الملف؛ تحقق من الأذونات والمساحة.',
    'Cannot save the file. Check folder permissions and free space.',
    '无法保存文件，请检查文件夹权限和可用空间。',
  ],
  'merge': [
    'صدا و تصویر در یک فایل ذخیره می‌شوند.',
    'سيُحفظ الصوت والفيديو في ملف واحد.',
    'Audio and video will be saved in one file.',
    '音频和视频将保存为一个文件。',
  ],
};
String tr(String locale, String key) =>
    words[key]?[['fa', 'ar', 'en', 'zh'].indexOf(locale)] ?? key;
